# These are the most generic rules we use, let's define it here.

$(XI_OBJDIR)/%.o : %.c
	@-mkdir -p "$(shell cygpath -a -m $(dir $@))"
	$(CC) $(XI_CFLAGS) -c $(shell cygpath -a -m $<) -o "$(shell cygpath -a -m $@)"

$(XI_OBJDIR)/%.d : %.c
	@-mkdir -p "$(shell cygpath -a -m $(dir $@))"
	@$(CC) $(XI_CFLAGS) -MM $< -MF "$(shell cygpath -a -m $@)" -MT $(@:.d=.o)

clean:
	$(RM) -rf $(XI_BINDIR)
	$(RM) -rf $(XI_OBJDIR)
